apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"] # pull_request
        - name: "only when RELEASE is created"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened']"
      bindings:
        - ref: github-pr-trigger-binding
      template:
        ref: github-pr-trigger-template