start: apply
#----------------------------------------------------------------------------

apply:
	kubectl apply -f pipeline.yaml
	kubectl apply -f triggertemplate.yaml
	kubectl apply -f triggerbinding.yaml
	kubectl apply -f eventlistener.yaml
